[build]
  publish = "."
  command = "node scripts/build.js && node scripts/generate-legal.js"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/*"
  to = "/es/:splat"
  status = 302
  conditions = {Language = ["es"]}
