const fs = require('fs');
const path = require('path');

const RAW_DIR = path.join(__dirname, '..', '..', 'Marketing_And_Products', 'product', 'prompts');
const TARGET_FILE = path.join(__dirname, '..', 'prompts.json');

// Ensure directories exist
if (!fs.existsSync(RAW_DIR)) {
  console.error("Source directory not found:", RAW_DIR);
  process.exit(1);
}

const mdFiles = fs.readdirSync(RAW_DIR).filter(f => f.endsWith('.md'));
let finalPrompts = [];

// Load existing prompts to avoid duplicates if necessary (or just overwrite if building fresh)
// For this task, we will preserve the existing "Gold Standard" prompts first.
if (fs.existsSync(TARGET_FILE)) {
    finalPrompts = JSON.parse(fs.readFileSync(TARGET_FILE, 'utf-8'));
}

const existingSlugs = new Set(finalPrompts.map(p => p.slug));

mdFiles.forEach(file => {
  const content = fs.readFileSync(path.join(RAW_DIR, file), 'utf-8');
  // Category mapping based on filename
  const catMap = {
    '01-content-creation.md': 'Marketing/Redes Sociales',
    '02-business-strategy.md': 'SaaS/Business',
    '03-coding-development.md': 'Programación/SaaS',
    '04-marketing-sales.md': 'Marketing/Redes Sociales',
    '05-productivity.md': 'Productividad',
    '06-education-learning.md': 'Educación',
    '07-creative-writing.md': 'Creatividad',
    '08-data-analysis.md': 'Finanzas/E-commerce',
    '09-personal-growth.md': 'Crecimiento Personal',
    '10-design-ux.md': 'Diseño/UX',
    '11-ai-automation-workflows.md': 'Programación/SaaS',
    '12-ai-money-making-blueprints.md': 'Finanzas/E-commerce'
  };
  
  const category = catMap[file] || 'General';
  
  // Split by ### items
  const items = content.split(/###\s+/).slice(1);
  
  items.forEach(item => {
    // Extract Title (first line)
    const lines = item.trim().split('\n');
    const title = lines[0].replace(/^\d+\.\s+/, '').trim();
    
    // Generate Slug
    let slug = title.toLowerCase()
      .replace(/[^\w\s-]/g, '')
      .replace(/\s+/g, '-')
      .replace(/-+/g, '-');
      
    if (existingSlugs.has(slug)) return; // Skip duplicates
    
    // Extract Prompt (between ```)
    const promptMatch = item.match(/```(?:\w+)?\n([\s\S]*?)```/);
    const promptText = promptMatch ? promptMatch[1].trim() : '';
    
    // Extract Pro Tip
    const tipMatch = item.match(/>\s*💡\s*\*\*Pro Tip:\*\*\s*(.*)/i);
    const proTip = tipMatch ? tipMatch[1].trim() : "Optimiza tus resultados iterando el prompt.";
    
    if (promptText && title) {
      finalPrompts.push({
        slug,
        title,
        category,
        prompt: promptText,
        exampleResult: "[Generated by AI]",
        useCaseEn: `High-value utility for ${category} tasks.`,
        useCaseEs: `Utilidad de alto valor para tareas de ${category}.`,
        proTipEn: proTip,
        proTipEs: `Consejo Pro: ${proTip}`
      });
      existingSlugs.add(slug);
    }
  });
});

fs.writeFileSync(TARGET_FILE, JSON.stringify(finalPrompts, null, 2));
console.log(`Migration complete. Total prompts in database: ${finalPrompts.length}`);
